### ISSUE TITLE
thanks for your reply. but I can't open

### ISSUE THREAD

**Issue by qkrrlduf96** [nepluno/SoapFilm3D#3]
Thanks for your kind reply. I did what you told me earlier, but when I initiated ./SoapFilm3D, it only shows me usage: ./SoapFilm3D option_file [save-outputs]

so... what should I put inside the ‘option_file’?  Is it Makefile?
when I put ‘Makefile’, it shows me ‘segmentation fault: 11

![error](https://user-images.githubusercontent.com/37322119/40487673-d871fb4e-5f9f-11e8-9b81-76258d526155.JPG)

**Comment by raymondyfei** [comment]
You can find option files in the assets folder. Of course an option file is not a Makefile.
You can Google what is a Makefile, and we don't provide basic training about unix compiling systems.
Please think and search before you file issues, since these are not any issues of the repository.
Thank you.
